services:
  - type: web
    name: alertdavao-backend
    env: node
    rootDir: UserSide/backends
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alertdavao-db
          property: connectionString
      - key: NODE_ENV
        value: production
    autoDeploy: false
